version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./personal-data/:/app/personal-data/
    environment:
      - APP_DATA_DIR=/app/personal-data/app_data
    env_file:
      - env/frontend.env.list

  backend:
    build:
      context: .
      dockerfile: src/ingest/Dockerfile
    volumes:
      - ./personal-data/:/app/personal-data/
    environment:
      - APP_DATA_DIR=/app/personal-data/app_data
    env_file:
      - env/ingest.env.list
      - conf/ingest.conf